Repository Kirankp25/TODO, pull requests merged in 2022-10, with the labels that each got.

#2 added css
  style.css
Labels: enhancement, good first issue, Hacktoberfest

#3 beautified the app
  index.html
  style.css
Labels: Beginner

#11 Add my changes to add a default text
  app.js
  index.html
  style.css
Labels: enhancement, Hacktoberfest

#19 footer updated
  index.html
  style.css
Labels: enhancement, Hacktoberfest

#21 Made some initial changes in html and css files
  index.html
  style.css
Labels: enhancement, Hacktoberfest

#20 CSS modified
  .vscode/settings.json
  index.html
  style.css
Labels: Hacktoberfest, Beginner

#29 UI changes, Bug Fixes and Added files
  app.js
  contributors.md
  index.html
  style.css
Labels: bug, enhancement, Hacktoberfest

#24 fix footer
  index.html
Labels: bug, Hacktoberfest

#37 added dark mode
  app.js
  index.html
  style.css
  theme.css
Labels: enhancement, Hacktoberfest

#46 fixed problem with input text color
  README.md
  index.html
Labels: documentation, Hacktoberfest
